### ISSUE TITLE
refの変更時にrefを再定義している

### ISSUE THREAD

**Issue by zorro901** [sasori7611san/vue_typescript#1]
https://github.com/sasori7611san/vue_typescript/blob/5fdf5f450a7f3ae50de051000b24a5a131ae5463/panel-system/src/components/PanelSystem.vue#L404

strColorRef = ref<string>('赤')  -> strColorRef.value = '赤'

refのvalueへアクセスして値のみ変更すると解決しました。

**Comment by sasori7611san** [comment]
zorro901様ありがとうございます。
指摘箇所を含む該当箇所を修正し、変数内の文字列が表示されていることを確認しました。
こちらでクローズさせていただきます。
